name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: mkdir
      run: mkdir build
    - name: cd
      run: cd build
    - name: ls
      run: ls
    - name: Cmake
      run: cmake ..
    - name: make
      run: make
