name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir build
    - name: build
      working-directory: ./build
      run: |
        cmake ..
        make
        ls
        
    - name: upload
      uses: actions/upload-artifact@v2
      with: 
        name: macos
        path: build/ 
